export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';
export const SET_USER_SERVICE_FAIL = 'SET_USER_SERVICE_FAIL';
export const SET_USER_SERVICE_SUCCESS = 'SET_USER_SERVICE_SUCCESS';
